GET http://localhost:5000/posts


###
POST http://localhost:5000/posts
Content-Type: application/json

{
    "title": "Post3",
    "content": "Vip pro dn 123",
    "author": "Dong Ky"
}

###
PUT http://localhost:5000/posts/update
Content-Type: application/json

{
   "_id": "60d74a64c58c6501b4d6ba17",
   "title": "1ba",
   "content": "1ba",
   "attachment": "" 
}

###
DELETE http://localhost:5000/posts
Content-Type: application/json 

{
    "_id": "60d687749789501d6fdf78e9"
}


###
DELETE http://localhost:5000/posts/all
